INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (1, 'Andorra', 'Andorra', 'AD', 'AND');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (2, 'Uni Emirat Arab', 'United Arab Emirates', 'AE', 'ARE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (3, 'Afganistan', 'Afghanistan', 'AF', 'AFG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (4, 'Antigua dan Barbuda', 'Antigua and Barbuda', 'AG', 'ATG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (5, 'Anguilla', 'Anguilla', 'AI', 'AIA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (6, 'Albania', 'Albania', 'AL', 'ALB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (7, 'Armenia', 'Armenia', 'AM', 'ARM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (8, 'Angola', 'Angola', 'AO', 'AGO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (9, 'Antartika', 'Antarctica', 'AQ', 'ATA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (10, 'Argentina', 'Argentina', 'AR', 'ARG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (11, 'Samoa Amerika', 'American Samoa', 'AS', 'ASM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (12, 'Austria', 'Austria', 'AT', 'AUT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (13, 'Australia', 'Australia', 'AU', 'AUS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (14, 'Aruba', 'Aruba', 'AW', 'ABW');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (15, 'Pulau Aland', 'Ã…land Islands', 'AX', 'ALA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (16, 'Azerbaijan', 'Azerbaijan', 'AZ', 'AZE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (17, 'Bosnia dan Herzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (18, 'Barbados', 'Barbados', 'BB', 'BRB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (19, 'Bangladesh', 'Bangladesh', 'BD', 'BGD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (20, 'Belgium', 'Belgium', 'BE', 'BEL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (21, 'Burkina Faso', 'Burkina Faso', 'BF', 'BFA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (22, 'Bulgaria', 'Bulgaria', 'BG', 'BGR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (23, 'Bahrain', 'Bahrain', 'BH', 'BHR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (24, 'Burundi', 'Burundi', 'BI', 'BDI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (25, 'Benin', 'Benin', 'BJ', 'BEN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (26, 'Saint Barthé lemy', 'Saint BarthÃ©lemy', 'BL', 'BLM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (27, 'Bermuda', 'Bermuda', 'BM', 'BMU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (28, 'Brunei Darussalam', 'Brunei Darussalam', 'BN', 'BRN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (29, 'Bolivia (Negara Plurinasional)', 'Bolivia (Plurinational State of)', 'BO', 'BOL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (30, 'Bonaire, Sint Eustatius dan Saba', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (31, 'Brazil', 'Brazil', 'BR', 'BRA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (32, 'Bahama', 'Bahamas', 'BS', 'BHS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (33, 'Bhutan', 'Bhutan', 'BT', 'BTN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (34, 'Pulau Bouvet', 'Bouvet Island', 'BV', 'BVT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (35, 'Botswana', 'Botswana', 'BW', 'BWA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (36, 'Belarus', 'Belarus', 'BY', 'BLR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (37, 'Belize', 'Belize', 'BZ', 'BLZ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (38, 'Kanada', 'Canada', 'CA', 'CAN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (39, 'Kepulauan Cocos (Keeling)', 'Cocos (Keeling) Islands', 'CC', 'CCK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (40, 'Republik Demokrasi Kongo', 'Democratic Republic of the Congo', 'CD', 'COD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (41, 'Republik Afrika Tengah', 'Central African Republic', 'CF', 'CAF');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (42, 'Kongo', 'Congo', 'CG', 'COG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (43, 'Swiss', 'Switzerland', 'CH', 'CHE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (44, 'Pantai Gading', 'CÃ´te d\'Ivoire', 'CI', 'CIV');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (45, 'Kepulauan Cook', 'Cook Islands', 'CK', 'COK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (46, 'Chili', 'Chile', 'CL', 'CHL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (47, 'Kamerun', 'Cameroon', 'CM', 'CMR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (48, 'Cina', 'China', 'CN', 'CHN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (49, 'Kolumbia', 'Colombia', 'CO', 'COL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (50, 'Kosta Rika', 'Costa Rica', 'CR', 'CRI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (51, 'Kuba', 'Cuba', 'CU', 'CUB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (52, 'Cabo Verde', 'Cabo Verde', 'CV', 'CPV');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (53, 'CuraÃ§ao', 'CuraÃ§ao', 'CW', 'CUW');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (54, 'Pulau Natal', 'Christmas Island', 'CX', 'CXR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (55, 'Siprus', 'Cyprus', 'CY', 'CYP');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (56, 'Czechia', 'Czechia', 'CZ', 'CZE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (57, 'Jerman', 'Germany', 'DE', 'DEU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (58, 'Djibouti', 'Djibouti', 'DJ', 'DJI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (59, 'Denmark', 'Denmark', 'DK', 'DNK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (60, 'Dominica', 'Dominica', 'DM', 'DMA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (61, 'Republik Dominika', 'Dominican Republic', 'DO', 'DOM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (62, 'Aljazair', 'Algeria', 'DZ', 'DZA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (63, 'Ekuador', 'Ecuador', 'EC', 'ECU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (64, 'Estonia', 'Estonia', 'EE', 'EST');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (65, 'Mesir', 'Egypt', 'EG', 'EGY');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (66, 'Sahara Barat', 'Western Sahara', 'EH', 'ESH');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (67, 'Eritrea', 'Eritrea', 'ER', 'ERI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (68, 'Spanyol', 'Spain', 'ES', 'ESP');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (69, 'Etiopia', 'Ethiopia', 'ET', 'ETH');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (70, 'Finlandia', 'Finland', 'FI', 'FIN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (71, 'Fiji', 'Fiji', 'FJ', 'FJI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (72, 'Kepulauan Falkland (Malvinas)', 'Falkland Islands (Malvinas)', 'FK', 'FLK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (73, 'Mikronesia (Negara Federasi)', 'Micronesia (Federated States of)', 'FM', 'FSM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (74, 'Kepulauan Faroe', 'Faroe Islands', 'FO', 'FRO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (75, 'Perancis', 'France', 'FR', 'FRA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (76, 'Gabon', 'Gabon', 'GA', 'GAB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (77, 'Kerajaan Inggris Raya dan Irlandia Utara', 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (78, 'Grenada', 'Grenada', 'GD', 'GRD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (79, 'Georgia', 'Georgia', 'GE', 'GEO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (80, 'Guyana Perancis', 'French Guiana', 'GF', 'GUF');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (81, 'Guernsey', 'Guernsey', 'GG', 'GGY');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (82, 'Ghana', 'Ghana', 'GH', 'GHA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (83, 'Gibraltar', 'Gibraltar', 'GI', 'GIB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (84, 'Tanah penggembalaan', 'Greenland', 'GL', 'GRL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (85, 'Gambia', 'Gambia', 'GM', 'GMB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (86, 'Guinea', 'Guinea', 'GN', 'GIN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (87, 'Guadeloupe', 'Guadeloupe', 'GP', 'GLP');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (88, 'Guinea ekuator', 'Equatorial Guinea', 'GQ', 'GNQ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (89, 'Yunani', 'Greece', 'GR', 'GRC');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (90, 'Georgia Selatan dan Kepulauan Sandwich Selatan', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (91, 'Guatemala', 'Guatemala', 'GT', 'GTM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (92, 'Guam', 'Guam', 'GU', 'GUM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (93, 'Guinea-Bissau', 'Guinea-Bissau', 'GW', 'GNB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (94, 'Guyana', 'Guyana', 'GY', 'GUY');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (95, 'Cina, Wilayah Administratif Khusus Hong Kong', 'China, Hong Kong Special Administrative Region', 'HK', 'HKG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (96, 'Pulau Heard dan Kepulauan McDonald', 'Heard Island and McDonald Islands', 'HM', 'HMD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (97, 'Honduras', 'Honduras', 'HN', 'HND');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (98, 'Kroasia', 'Croatia', 'HR', 'HRV');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (99, 'Haiti', 'Haiti', 'HT', 'HTI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (100, 'Hungaria', 'Hungary', 'HU', 'HUN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (101, 'Indonesia', 'Indonesia', 'ID', 'IDN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (102, 'Irlandia', 'Ireland', 'IE', 'IRL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (103, 'Israel', 'Israel', 'IL', 'ISR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (104, 'Pulau manusia', 'Isle of Man', 'IM', 'IMN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (105, 'India', 'India', 'IN', 'IND');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (106, 'Wilayah Samudra Hindia Britania', 'British Indian Ocean Territory', 'IO', 'IOT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (107, 'Irak', 'Iraq', 'IQ', 'IRQ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (108, 'Iran (Republik Islam)', 'Iran (Islamic Republic of)', 'IR', 'IRN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (109, 'Islandia', 'Iceland', 'IS', 'ISL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (110, 'Italia', 'Italy', 'IT', 'ITA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (111, 'Jersey', 'Jersey', 'JE', 'JEY');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (112, 'Jamaika', 'Jamaica', 'JM', 'JAM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (113, 'Yordania', 'Jordan', 'JO', 'JOR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (114, 'Jepang', 'Japan', 'JP', 'JPN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (115, 'Kenya', 'Kenya', 'KE', 'KEN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (116, 'Kirgistan', 'Kyrgyzstan', 'KG', 'KGZ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (117, 'Kamboja', 'Cambodia', 'KH', 'KHM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (118, 'Kiribati', 'Kiribati', 'KI', 'KIR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (119, 'Komoro', 'Comoros', 'KM', 'COM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (120, 'Saint Kitts dan Nevis', 'Saint Kitts and Nevis', 'KN', 'KNA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (121, 'Republik Rakyat Demokratik Korea (Korea Utara)', 'Democratic People\'s Republic of Korea', 'KP', 'PRK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (122, 'Republik Korea (Korea Selatan)', 'Republic of Korea', 'KR', 'KOR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (123, 'Kuwait', 'Kuwait', 'KW', 'KWT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (124, 'Pulau cayman', 'Cayman Islands', 'KY', 'CYM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (125, 'Kazakhstan', 'Kazakhstan', 'KZ', 'KAZ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (126, 'Republik Demokratik Rakyat Laos', 'Lao People\'s Democratic Republic', 'LA', 'LAO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (127, 'Libanon', 'Lebanon', 'LB', 'LBN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (128, 'Saint Lucia', 'Saint Lucia', 'LC', 'LCA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (129, 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (130, 'Srilanka', 'Sri Lanka', 'LK', 'LKA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (131, 'Liberia', 'Liberia', 'LR', 'LBR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (132, 'Lesotho', 'Lesotho', 'LS', 'LSO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (133, 'Lithuania', 'Lithuania', 'LT', 'LTU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (134, 'Luksemburg', 'Luxembourg', 'LU', 'LUX');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (135, 'Latvia', 'Latvia', 'LV', 'LVA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (136, 'Libya', 'Libya', 'LY', 'LBY');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (137, 'Maroko', 'Morocco', 'MA', 'MAR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (138, 'Monako', 'Monaco', 'MC', 'MCO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (139, 'Republik Moldova', 'Republic of Moldova', 'MD', 'MDA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (140, 'Montenegro', 'Montenegro', 'ME', 'MNE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (141, 'Saint Martin (Bagian Prancis)', 'Saint Martin (French Part)', 'MF', 'MAF');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (142, 'Madagaskar', 'Madagascar', 'MG', 'MDG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (143, 'Pulau Marshall', 'Marshall Islands', 'MH', 'MHL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (144, 'Bekas Republik Yugoslavia Makedonia', 'The former Yugoslav Republic of Macedonia', 'MK', 'MKD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (145, 'Mali', 'Mali', 'ML', 'MLI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (146, 'Myanmar', 'Myanmar', 'MM', 'MMR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (147, 'Mongolia', 'Mongolia', 'MN', 'MNG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (148, 'Cina, Wilayah Administratif Khusus Makao', 'China, Macao Special Administrative Region', 'MO', 'MAC');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (149, 'Kepulauan Mariana Utara', 'Northern Mariana Islands', 'MP', 'MNP');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (150, 'Martinique', 'Martinique', 'MQ', 'MTQ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (151, 'Mauritania', 'Mauritania', 'MR', 'MRT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (152, 'Montserrat', 'Montserrat', 'MS', 'MSR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (153, 'Malta', 'Malta', 'MT', 'MLT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (154, 'Mauritius', 'Mauritius', 'MU', 'MUS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (155, 'Maladewa', 'Maldives', 'MV', 'MDV');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (156, 'Malawi', 'Malawi', 'MW', 'MWI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (157, 'Meksiko', 'Mexico', 'MX', 'MEX');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (158, 'Malaysia', 'Malaysia', 'MY', 'MYS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (159, 'Mozambik', 'Mozambique', 'MZ', 'MOZ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (160, 'Namibia', 'Namibia', 'NA', 'NAM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (161, 'Kaledonia Baru', 'New Caledonia', 'NC', 'NCL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (162, 'Niger', 'Niger', 'NE', 'NER');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (163, 'Pulau Norfolk', 'Norfolk Island', 'NF', 'NFK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (164, 'Nigeria', 'Nigeria', 'NG', 'NGA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (165, 'Nikaragua', 'Nicaragua', 'NI', 'NIC');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (166, 'Belanda', 'Netherlands', 'NL', 'NLD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (167, 'Norway', 'Norway', 'NO', 'NOR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (168, 'Nepal', 'Nepal', 'NP', 'NPL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (169, 'Nauru', 'Nauru', 'NR', 'NRU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (170, 'Niue', 'Niue', 'NU', 'NIU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (171, 'Selandia Baru', 'New Zealand', 'NZ', 'NZL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (172, 'Oman', 'Oman', 'OM', 'OMN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (173, 'Panama', 'Panama', 'PA', 'PAN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (174, 'Peru', 'Peru', 'PE', 'PER');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (175, 'Polinesia Perancis', 'French Polynesia', 'PF', 'PYF');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (176, 'Papua Nugini', 'Papua New Guinea', 'PG', 'PNG');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (177, 'Filipina', 'Philippines', 'PH', 'PHL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (178, 'Pakistan', 'Pakistan', 'PK', 'PAK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (179, 'Polandia', 'Poland', 'PL', 'POL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (180, 'Saint Pierre dan Miquelon', 'Saint Pierre and Miquelon', 'PM', 'SPM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (181, 'Pitcairn', 'Pitcairn', 'PN', 'PCN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (182, 'Puerto Riko', 'Puerto Rico', 'PR', 'PRI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (183, 'Negara Palestina', 'State of Palestine', 'PS', 'PSE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (184, 'Portugal', 'Portugal', 'PT', 'PRT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (185, 'Palau', 'Palau', 'PW', 'PLW');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (186, 'Paraguay', 'Paraguay', 'PY', 'PRY');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (187, 'Qatar', 'Qatar', 'QA', 'QAT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (188, 'Union ©', 'RÃ©union', 'RE', 'REU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (189, 'Rumania', 'Romania', 'RO', 'ROU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (190, 'Serbia', 'Serbia', 'RS', 'SRB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (191, 'Federasi Rusia', 'Russian Federation', 'RU', 'RUS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (192, 'Rwanda', 'Rwanda', 'RW', 'RWA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (193, 'Arab Saudi', 'Saudi Arabia', 'SA', 'SAU');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (194, 'Pulau Solomon', 'Solomon Islands', 'SB', 'SLB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (195, 'Seychelles', 'Seychelles', 'SC', 'SYC');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (196, 'Sudan', 'Sudan', 'SD', 'SDN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (197, 'Swedia', 'Sweden', 'SE', 'SWE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (198, 'Singapura', 'Singapore', 'SG', 'SGP');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (199, 'Saint Helena', 'Saint Helena', 'SH', 'SHN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (200, 'Slovenia', 'Slovenia', 'SI', 'SVN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (201, 'Kepulauan Svalbard dan Jan Mayen', 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (202, 'Slovakia', 'Slovakia', 'SK', 'SVK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (203, 'Sierra Leone', 'Sierra Leone', 'SL', 'SLE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (204, 'San Marino', 'San Marino', 'SM', 'SMR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (205, 'Senegal', 'Senegal', 'SN', 'SEN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (206, 'Somalia', 'Somalia', 'SO', 'SOM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (207, 'Suriname', 'Suriname', 'SR', 'SUR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (208, 'Sudan Selatan', 'South Sudan', 'SS', 'SSD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (209, 'Sao Tome dan Principe', 'Sao Tome and Principe', 'ST', 'STP');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (210, 'El Salvador', 'El Salvador', 'SV', 'SLV');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (211, 'Sint Maarten (bagian Belanda)', 'Sint Maarten (Dutch part)', 'SX', 'SXM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (212, 'Republik Arab Syria', 'Syrian Arab Republic', 'SY', 'SYR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (213, 'Swaziland', 'Swaziland', 'SZ', 'SWZ');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (214, 'Kepulauan Turks dan Caicos', 'Turks and Caicos Islands', 'TC', 'TCA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (215, 'Chad', 'Chad', 'TD', 'TCD');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (216, 'Wilayah Selatan Prancis', 'French Southern Territories', 'TF', 'ATF');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (217, 'Untuk pergi', 'Togo', 'TG', 'TGO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (218, 'Thailand', 'Thailand', 'TH', 'THA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (219, 'Tajikistan', 'Tajikistan', 'TJ', 'TJK');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (220, 'Tokelau', 'Tokelau', 'TK', 'TKL');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (221, 'Timor-Leste', 'Timor-Leste', 'TL', 'TLS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (222, 'Turkmenistan', 'Turkmenistan', 'TM', 'TKM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (223, 'Tunisia', 'Tunisia', 'TN', 'TUN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (224, 'Tonga', 'Tonga', 'TO', 'TON');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (225, 'Turki', 'Turkey', 'TR', 'TUR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (226, 'Trinidad dan Tobago', 'Trinidad and Tobago', 'TT', 'TTO');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (227, 'Tuvalu', 'Tuvalu', 'TV', 'TUV');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (228, 'Taiwan', 'Taiwan', 'TW', 'TWN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (229, 'Republik Persatuan Tanzania', 'United Republic of Tanzania', 'TZ', 'TZA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (230, 'Ukraina', 'Ukraine', 'UA', 'UKR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (231, 'Uganda', 'Uganda', 'UG', 'UGA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (232, 'Kepulauan Terluar Kecil Amerika Serikat', 'United States Minor Outlying Islands', 'UM', 'UMI');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (233, 'Amerika Serikat', 'United States of America', 'US', 'USA');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (234, 'Uruguay', 'Uruguay', 'UY', 'URY');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (235, 'Uzbekistan', 'Uzbekistan', 'UZ', 'UZB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (236, 'Takhta Suci', 'Holy See', 'VA', 'VAT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (237, 'Saint Vincent dan Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (238, 'Venezuela (Republik Bolivarian)', 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (239, 'Kepulauan Virgin Inggris', 'British Virgin Islands', 'VG', 'VGB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (240, 'Kepulauan Virgin Amerika Serikat', 'United States Virgin Islands', 'VI', 'VIR');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (241, 'Vietnam', 'Viet Nam', 'VN', 'VNM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (242, 'Vanuatu', 'Vanuatu', 'VU', 'VUT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (243, 'Kepulauan Wallis dan Futuna', 'Wallis and Futuna Islands', 'WF', 'WLF');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (244, 'Samoa', 'Samoa', 'WS', 'WSM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (245, 'Yaman', 'Yemen', 'YE', 'YEM');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (246, 'Mayotte', 'Mayotte', 'YT', 'MYT');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (247, 'Afrika Selatan', 'South Africa', 'ZA', 'ZAF');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (248, 'Zambia', 'Zambia', 'ZM', 'ZMB');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (249, 'Zimbabwe', 'Zimbabwe', 'ZW', 'ZWE');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (251, 'Kosovo', 'Kosovo', 'XK', 'XKS');
INSERT INTO `BP2_R_NEGARA`(`NEG_ID`, `NEG_NAME`, `NEG_ENNAME`, `NEG_ISO2`, `NEG_ISO3`) VALUES (252, 'Vatican City', 'Vatican City', 'VA', 'VAT');
